### ISSUE TITLE
Connection flow is cumbersome

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/news-iOS-App#13]
Currently you have to do 3 things after putting in your server, username and password:
1. tap »Connect« to actually connect
2. tap »Done« to get out of that view
3. pull to refresh to actually get the feeds

Now apart from the fact that it’s really common to press the »Done« button accidentally and have your put in values lost (should be preserved!), it’s a bit of a long process.

Instead, after tapping the »Connect« button and the connection is successful, the view should automatically switch to the feed list and it should automatically refresh/load the feeds.

**Comment by phedlund** [comment]
The flow has been simplified for the next release.

**Comment by jancborchardt** [comment]
Cool, thank you!
