### ISSUE TITLE
Unread totals don't always update correctly

### ISSUE THREAD

**Issue by nestsman** [owncloud/news-iOS-App#44]
Steps:

1. Go into a folder that has more than one feed and unread articles
2. Tap on one specific feed
3. Mark all of the articles as read
4. Go back to the feeds in the folder
5. You will notice that there are zero unread articles for that particular feed
6. Go back to the feeds list
7. The unread count for the folder you were just in is not correct
8. Go back into that same folder
9. Swipe down so it does a refresh with the server
10. Go back to the feed list
11. You will notice that total is not updated

**Comment by rakekniven** [comment]
Having similar issue here on two iOS 8.4.1 devices.
Server is at v8.1.1 and news app at version 6.0.1

Unread counts of some feeds changes after some seconds.  Total count is wrong compared to web UI.
Now I refresh feeds and count is the same.
Closing app.
Opening app again and whole story starts again.
What else information should I provide?
Should I do a video to show my issue?

**Comment by rakekniven** [comment]
Still happens on some devices. Just installed app on iPad Pro with iOS 9.1 and it happens.
