### ISSUE TITLE
News app looses authentication to server occasionally

### ISSUE THREAD

**Issue by HenningSchulz** [owncloud/news-iOS-App#49]
Hi,
Sometimes I get the red error that I´m not authenticated. Then I have to go to the options menu and connect again without changing my login data. Then it works again for a while until the error comes up again. Then I have to do this procedure over and over again. 

My server doesn´t restart or changes anything except the IP because of 24h disconnect... Maybe thats the cause? I´ll count how often this happends per day. It seems to be more than one time but I´ll count from now on :)

That happends with my new Freenas server as well as with my raspberry pi before.

**Comment by eilersKevin** [comment]
I have the same problem. Basically every time I start the app, I have to reconnect to the server.

**Comment by KeiOtori** [comment]
Same issue: i am starting the app, and it shows red alert "Not authorized"; App shows it only, when it starts _without_ "loading screen" with news logo. Maybe it losts the auth(z) token, and this token can't update without full app restart?
