### ISSUE TITLE
Configure sort order

### ISSUE THREAD

**Issue by hamstercat** [owncloud/news-iOS-App#62]
In the News app in ownCloud, it's now possible to sort feeds in reverse order (from oldest to latest). Would it be possible to implement the same behavior in this app?

**Comment by bfarkas** [comment]
:+1: 
I would also like to see that feature. Anything we can do to help? :)

**Comment by phedlund** [comment]
> Anything we can do to help? :)

A pull request would work 😄.

**Comment by rakekniven** [comment]
Latest release of news app v6.0.3 has the feature to pin feeds. 
Ideally news-iOS-app would show order from news app.

**Comment by phedlund** [comment]
> Ideally news-iOS-app would show order from news app.

File an issue with the news app to add this to the client API. Otherwise there is nothing I can do.

**Comment by rakekniven** [comment]
Looks like feature is possible. See https://github.com/owncloud/news/wiki/Feeds-1.2

**Comment by phedlund** [comment]
Added in version 3.11.0.

**Comment by rakekniven** [comment]
Great thank you.
