### ISSUE TITLE
clang: error: no such file or directory MMDrawerBarButtonItem.m'

### ISSUE THREAD

**Issue by inix** [owncloud/news-iOS-App#63]
Xcode 6.1 open iOCNews.xcodeproj and click Run in iPhone6 simulator,it prompted:

<pre>
Missing dependency target "pcre (from pcre.xcodeproj)"

CompileC /Users/test/Library/Developer/Xcode/DerivedData/iOCNews-gibozwvuwtibuwguzvufzbglrlze/Build/Intermediates/iOCNews.build/Debug-iphonesimulator/iOCNews.build/Objects-normal/x86_64/MMDrawerBarButtonItem.o MMDrawerController/MMDrawerController/MMDrawerBarButtonItem.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/test/Documents/news-iOS-App
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wno-bool-conversion -Wenum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -DDEBUG=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -fobjc-abi-version=2 -fobjc-legacy-dispatch -mios-simulator-version-min=8.0 -I/Users/test/Library/Developer/Xcode/DerivedData/iOCNews-gibozwvuwtibuwguzvufzbglrlze/Build/Intermediates/iOCNews.build/Debug-iphonesimulator/iOCNews.build/iOCNews.hmap -I/Users/test/Documents/news-iOS-App/iOSPorts/include -I/Users/test/Library/Developer/Xcode/DerivedData/iOCNews-gibozwvuwtibuwguzvufzbglrlze/Build/Products/Debug-iphonesimulator/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk/usr/include/libxml2 -I/Users/test/Library/Developer/Xcode/DerivedData/iOCNews-gibozwvuwtibuwguzvufzbglrlze/Build/Intermediates/iOCNews.build/Debug-iphonesimulator/iOCNews.build/DerivedSources/x86_64 -I/Users/test/Library/Developer/Xcode/DerivedData/iOCNews-gibozwvuwtibuwguzvufzbglrlze/Build/Intermediates/iOCNews.build/Debug-iphonesimulator/iOCNews.build/DerivedSources -F/Users/test/Library/Developer/Xcode/DerivedData/iOCNews-gibozwvuwtibuwguzvufzbglrlze/Build/Products/Debug-iphonesimulator -F/Users/peter/Projects/iOCNews -include /Users/test/Library/Developer/Xcode/DerivedData/iOCNews-gibozwvuwtibuwguzvufzbglrlze/Build/Intermediates/PrecompiledHeaders/iOCNews-Prefix-dapmqjnrkloscwcdfnxllqusctlq/iOCNews-Prefix.pch -MMD -MT dependencies -MF /Users/test/Library/Developer/Xcode/DerivedData/iOCNews-gibozwvuwtibuwguzvufzbglrlze/Build/Intermediates/iOCNews.build/Debug-iphonesimulator/iOCNews.build/Objects-normal/x86_64/MMDrawerBarButtonItem.d --serialize-diagnostics /Users/test/Library/Developer/Xcode/DerivedData/iOCNews-gibozwvuwtibuwguzvufzbglrlze/Build/Intermediates/iOCNews.build/Debug-iphonesimulator/iOCNews.build/Objects-normal/x86_64/MMDrawerBarButtonItem.dia -c /Users/test/Documents/news-iOS-App/MMDrawerController/MMDrawerController/MMDrawerBarButtonItem.m -o /Users/test/Library/Developer/Xcode/DerivedData/iOCNews-gibozwvuwtibuwguzvufzbglrlze/Build/Intermediates/iOCNews.build/Debug-iphonesimulator/iOCNews.build/Objects-normal/x86_64/MMDrawerBarButtonItem.o

clang: error: no such file or directory: '/Users/test/Documents/news-iOS-App/MMDrawerController/MMDrawerController/MMDrawerBarButtonItem.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

</pre>

**Comment by phedlund** [comment]
You need to do a recursive clone to get all the submodules.
`git clone --recursive `
