### ISSUE TITLE
Feed icons are messed up

### ISSUE THREAD

**Issue by rakekniven** [owncloud/news-iOS-App#65]
Some feeds have incorrect icons.
They have icons from other feeds. They are mixed

![img_4438-2](https://cloud.githubusercontent.com/assets/2069590/9701285/55d6833e-5422-11e5-9e11-4a04b0f46bc5.PNG)
Web UI of news app looks good.

Using latest version from iOS store.
Same on two devices connected to same ownCloud instance (v8.1.1). News app version v6.0.1

**Comment by phedlund** [comment]
The latest version of the app uses a new mechanism to fetch the favicons. If you upgraded from a previous version the issue should resolve itself if you delete and reinstall the app.

**Comment by rakekniven** [comment]
Hello Peter,

reinstalling the app solved issue.
