### ISSUE TITLE
No. of starred items is not equal to web UI

### ISSUE THREAD

**Issue by rakekniven** [owncloud/news-iOS-App#68]
I run 4 iOS devices and counter for starred items are different on all of them.
Overall counter of items and detailed counter for each feed are correct.

Is starred items counter something different or should counter value be same as on web UI?

News app version: 6.1.1
ownCloud server version: 8.2.2

**Comment by phedlund** [comment]
Starring and unstarring of articles should sync and thus be the same. I will investigate.

**Comment by rakekniven** [comment]
Hmmh. Had a look at my devices the last hours. 3-4 month ago sync of starred items was ok. New entries are doubled. Not in article list, just at counter at the left (root level).

**Comment by rakekniven** [comment]
Just encountered following behavior on my iPhone running iOS 9.1:
Starred items are only added local on device. No sync to server. Played around with different articles of different feeds.
