### ISSUE TITLE
Update shows "server error"

### ISSUE THREAD

**Issue by rakekniven** [owncloud/news-iOS-App#69]
Hello Peter,

just updated my iOS to latest version 3.4 without changing anything.
Now I get a red error on refreshing telling me:

Error updating feeds
The server responded 'server error' and the error reported was 'The certificate for this server is invalid. You might be connecting to a server that is pretending to be xxx which could put your confidential information at risk.'.

Haven't touch my ownCloud server 8.2.2 for many days

**Comment by ghostbzh** [comment]
Hello,

I have the same issue, with an owncloud 8.1.3 server and SSL (self-signed certificate).

**Comment by phedlund** [comment]
Unfortunately I missed that Apple has further tightened the rules for untrusted certificates and URLs when building with the latest toolset. It should be possible to work around. I will submit an update as soon as possible.

I can also recommend getting a trusted certificate from letsencrypt.org. Free and open source.

**Comment by phedlund** [comment]
Updated submitted to Apple for review.

**Comment by rakekniven** [comment]
Forgot to mention that I did a change serverside. Updated news app to version 7.1.1

Will provide feedback as soon as app update is available.
