### ISSUE TITLE
Unable to authenticate after upgrade to OC9.0

### ISSUE THREAD

**Issue by TheReal1604** [owncloud/news-iOS-App#70]
Hey guys,

after the upgrade to owncloud 9.0 the authentication with the Cloudnews app is not working anymore. I only get "request failed: 401 unauthorised" 

In the backend I use ldap auth in owncloud. 

Did you have any suggestions? 

Thanks in advance. 

TheReal

**Comment by TheReal1604** [comment]
Hey Guys,

here is the log entry in owncloud.log:

> {"reqId":"Utx+ERYXWUEik1mnJr\/A","remoteAddr":"192.168.9.15","app":"user_ldap","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"No user available for the given login name.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php(120): OCA\\\\user_ldap\\\\USER_LDAP->getLDAPUserByLoginName('Franzi')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user\\\/manager.php(183): OCA\\\\user_ldap\\\\USER_LDAP->checkPassword(*** username and password replaced ***)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user\\\/session.php(219): OC\\\\User\\\\Manager->checkPassword(*** username and password replaced ***)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/security\\\/corsmiddleware.php(91): OC\\\\User\\\\Session->login(*** username and password replaced ***)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/middleware\\\/middlewaredispatcher.php(92): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\CORSMiddleware->beforeController(Object(OCA\\\\News\\\\Controller\\\\UtilityApiController), 'version')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\News\\\\Controller\\\\UtilityApiController), 'version')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\News\\\\Controller\\\\UtilityApiController), 'version')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('UtilityApiContr...', 'version', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(273): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/news\\\/api\\\/...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#12 
{main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Line\":105}","level":3,"time":"2016-03-14T18:15:48+00:00"}

**Comment by phedlund** [comment]
Looks like an LDAP issue to me: 

> No user available for the given login name

**Comment by TheReal1604** [comment]
Hey Peter,

via the web Page i can authenticate with my ldap credentials.

But I got problems with the owncloud app too.



Am 15.03.2016 um 01:46 schrieb Peter Hedlund <notifications@github.com<mailto:notifications@github.com>>:


Looks like an LDAP issue to me:

No user available for the given login name

-

**Comment by nasli** [comment]
Hi @TheReal1604, 
sorry to hear that, we can not reproduce it here, could you send us a test account to apps@owncloud.com thanks!

**Comment by nasli** [comment]
Sorry @TheReal1604, I misread, I thought it was related the iOS OC app

**Comment by TheReal1604** [comment]
Hey @nasli all ios apps are affected by the issue. (Cloudnews and OwnCloud ios App) Openend a issue at owncloud\core too.. (https://github.com/owncloud/core/issues/23248) 

It seems that this is a core issue or an issue with the ldap_app.

**Comment by TheReal1604** [comment]
fixed in https://github.com/owncloud/core/issues/23248 - closing.
