### ISSUE TITLE
Unable to hide settings dialog without choosing submenu

### ISSUE THREAD

**Issue by rakekniven** [owncloud/news-iOS-App#76]
1. Press settings (gear wheel top right)
2. Following dialog comes up
![2016-12-30 13-21-58 5974](https://cloud.githubusercontent.com/assets/2069590/21565044/50c0923a-ce93-11e6-81f5-3ac91b88a529.png)
3. I am unable to close dialog. I have to select "settings" and close it from there.

**Comment by phedlund** [comment]
Fixed in version 3.11.0.
