### ISSUE TITLE
Show app version somewhere in settings dialog

### ISSUE THREAD

**Issue by rakekniven** [owncloud/news-iOS-App#77]
Please show app version inside app.

Idea:
Add section "App version" below "Support". Same layout as for "Contact" can be used.

![2016-12-30 13-26-57 5975](https://cloud.githubusercontent.com/assets/2069590/21565131/6cd3e480-ce94-11e6-8baf-208d5934f3e0.png)

**Comment by phedlund** [comment]
![screen shot 2016-12-30 at 8 38 52 am](https://cloud.githubusercontent.com/assets/884639/21568683/795c7858-ce6b-11e6-9f6c-baf51ab76726.png)

This information is already shown under CloudNews in the iOS Settings app.
