### ISSUE TITLE
Scrolling list of news no smooth on iPhone SE

### ISSUE THREAD

**Issue by yopzolo** [owncloud/news-iOS-App#85]
since version 3.8.1 scrolling the list of news is not smooth

I'm using an iPhone SE
I tried different themes and the result is the same

I was an iOS developper in the past, shadows and rounded corners on cells create this. can you work on enhancing the scrolling performance, please. If it's smooth on more recent phones, it sure wastes user batteries.

**Comment by phedlund** [comment]
Hmm, I see what you mean. I mostly use an iPad where the scrolling is very good. I'll see what I can do.

**Comment by yopzolo** [comment]
Just bought an Iphone 11 (last one A13 ship) and I still see the problem. I admit having a lot of feeds, lots of unread articles. Switching to fiery feeds now (Free for equivalent features) since there was no new features here and the problem is not fixed. 
Btw you're likely loading to much in memory and eventually touching the CALayer which is known having performances issues with shadows and corners.

**Comment by phedlund** [comment]
Selecting All Articles (which for me also means thousands) I can't see any scrolling lag on my XS Max. Are you saying the lag is when the app marks unread article read? Is the lag affected by turning off thumbnails?
